import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideToast from "@/components/other-components/client-side-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Roles Permission",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ClientSideToast />
      </body>
    </html>
  );
}
